### ISSUE TITLE
Project Milestone Task List 

### ISSUE THREAD

**Issue by ebeshero** [spookybeetle/foundingOfPSB#4]
- [ ] Jaxon could be for the next few days reviewing the document images and 
     - [ ] listing persons and organizations, maybe just as a New Issue on this repo. (This can easily be "folded into" the XML code for the project after the milestone. 
     - [ ] Look them up one by one in Google (work on refining searches): example "Lou Balmer Penn State Behrend" Retrieve links and add them 
     - [ ] Can you dig up birth dates, death dates? 
     - [ ] mention a few exciting things they seem to have been doing around the years your project is focusing on (1950s)?    @JaxAbele 

- [ ] Milo can be working on improving the schema and creating the document structure for standard lists of named entities (organizations, people, etc. NOTE that the research we're setting @JaxAbele on should be added to this document, so really just concentrate on its structure until you can meet.   
     - [ ]  At your next project meeting (say, after this milestone is due), work on reviewing @JaxAbele 's research and incorporate it into the XML for lists of people, organizations, etc. @spookybeetle
     
- [ ] Will can continue working on the website, but should get involved in discussing the XML structure and what we can do with this code working with XSLT.  @WillStill
